// <auto-generated />
using System;
using GerenciamentoFinanceiroMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciamentoFinanceiroMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250813112053_CriandoTabelasDB")]
    partial class CriandoTabelasDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciamentoFinanceiroMVC.Models.Categoria", b =>
                {
                    b.Property<string>("CategoriaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = "educacao",
                            NomeCategoria = "Educação"
                        },
                        new
                        {
                            CategoriaId = "salario",
                            NomeCategoria = "Salário"
                        },
                        new
                        {
                            CategoriaId = "viagem",
                            NomeCategoria = "Viagem"
                        },
                        new
                        {
                            CategoriaId = "mercado",
                            NomeCategoria = "Mercado"
                        },
                        new
                        {
                            CategoriaId = "comissao",
                            NomeCategoria = "Comissão"
                        });
                });

            modelBuilder.Entity("GerenciamentoFinanceiroMVC.Models.Financeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoriaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransacaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TransacaoId");

                    b.ToTable("Financas");
                });

            modelBuilder.Entity("GerenciamentoFinanceiroMVC.Models.Transacao", b =>
                {
                    b.Property<string>("TransacaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeTransacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransacaoId");

                    b.ToTable("Transacoes");

                    b.HasData(
                        new
                        {
                            TransacaoId = "ganho",
                            NomeTransacao = "Ganho"
                        },
                        new
                        {
                            TransacaoId = "gasto",
                            NomeTransacao = "Gasto"
                        });
                });

            modelBuilder.Entity("GerenciamentoFinanceiroMVC.Models.Financeiro", b =>
                {
                    b.HasOne("GerenciamentoFinanceiroMVC.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciamentoFinanceiroMVC.Models.Transacao", "Transacao")
                        .WithMany()
                        .HasForeignKey("TransacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Transacao");
                });
#pragma warning restore 612, 618
        }
    }
}
